.lgtm.yml, build.gradle, javacutil/build.gradle
I've only done this for compiling and the Junit tests.  We'll need to do something similar for jtreg tests and other test targets.
=> Update Gradle scripts to use errorprone compiler.

checker/src/main/java/org/checkerframework/checker/initialization/InitializationTransfer.java
The completer of a symbol is compared with 'NULL_COMPLETER' instead of 'null'.
Counts of errors before fix:
Tests : 161
Failures : 12
Ignored : 0
Failed Tests : 
IndexTest. run[index]
LockSafeDefaultsTest. run[lock-safedefaults]
LockTest. run[lock]
NestedAggregateCheckerTest. run[all-systems]
NullnessFbcTest. run[all-systems]
NullnessFbcTest. run[nullness/init]
NullnessFbcTest. run[nullness]
NullnessRawnessTest. run[all-systems]
NullnessRawnessTest. run[nullness/init]
NullnessRawnessTest. run[nullness]
NullnessReflectionTest. run[nullness-reflection]
TaintingTest. run[tainting]
Counts of errors after fix:
Tests : 161
Failures : 10
Ignored : 0
Failed Tests : 
IndexTest. run[index]
LockSafeDefaultsTest. run[lock-safedefaults]
LockTest. run[lock]
NestedAggregateCheckerTest. run[all-systems] …
=> Fix NullnessFbc Test : Compare with NULL_COMPLETER

build.gradle
This fix solves the error : 
```
Execution failed for task ':checker-framework:framework:checkPurity'.
> invalid flag: -source 8
```
=> Fixes invalid flag error in checkPurity task

framework/src/main/java/org/checkerframework/common/reflection/DefaultReflectionResolver.java
**Before fix :** 
- On running ./gradlew alltests :
Total tests: 161
Failures: 4
Skipped: 0
770 out of 776 total expected diagnostics were found
15 total unexpected diagnostics were found
- On running ./gradlew framework:alltests
Tests : 359
Failures : 30
Ignored : 1
**After fix :** 
- On running ./gradlew alltests : 
Total tests: 161
Failures: 3
Skipped: 0
770 out of 776 total expected diagnostics were found
7 total unexpected diagnostics were found
- On running ./gradlew framework:alltests
Tests : 359
Failures : 29
Ignored : 1
=> Fixes error due to changed method signature of loadClass in Resolve.java

framework/src/main/java/org/checkerframework/framework/type/BoundsInitializer.java
Fixes issues while running 'Tainting Test : Issue1942.java' by using un-annotated type variables as key to `typevars` map,  both when adding or looking something in the map.
The following failures were solved : 
```
1 expected diagnostic was not found :
Issue1111.java:15: error: (argument.type.incompatible)
2 unexpected diagnostics were found :
Issue1942.java:14: error: (override.param.invalid)
:- 1:other: error: AsSuperVisitor: type is not an erased subtype of supertype.
type: @Untainted Object
superType: @Tainted Integer
Compilation unit: tests/tainting/Issue1111.java
Last visited tree at line 13 column 15:
void foo2(Box<@Untainted ? super Integer> box, List<Integer> list) { 
```
=> Uses un-annotated type variables as key to typevars map

build.gradle
This fixes the failure of group "misc" in [job 87.1](https://travis-ci.org/eisop/checker-framework/jobs/495124108): `Cannot cast object 'taglet classes' with class 'org.gradle.api.internal.tasks.DefaultSourceSetOutput_Decorated' to class 'java.io.File'`. A successful build is [here](https://travis-ci.org/zhangjiangqige/checker-framework/jobs/500556342).
By calling `getFiles` we can get a `Set<File>` which is convertible.
=> Fix build job of group "misc"

framework-test/src/main/java/org/checkerframework/framework/test/TestConfigurationBuilder.java, framework-test/src/main/java/org/checkerframework/framework/test/TypecheckExecutor.java, framework/src/main/java/org/checkerframework/framework/stub/StubGenerator.java
This fixes the missing module error of checker-framework-inference https://github.com/eisop/checker-framework-inference/pull/1#issuecomment-492868310 .
It's also possible to add these parameters to [TypecheckExecutor.compile](https://github.com/eisop/checker-framework/blob/00a9acc3e3795879c1a5ca6cc3a6cf2086654023/framework-test/src/main/java/org/checkerframework/framework/test/TypecheckExecutor.java#L31) instead of here, but I'm not sure which is more appropriate.
=> Add -source 8 and -target 8 when building the default TestConfiguration

.travis-build.sh
This PR is a part of the fix for the downstream build. Now the build job would use eisop/guava instead of typetools/guava.
In addition to this, a new branch `cf-master` needs to be created in the repo guava for the build to succeed, because of this [commit](https://github.com/eisop/checker-framework/commit/8f9b00afbc1ccce1a0bc0a76883ac17db92174eb). Creating `cf-master` from `master` would do the job.
=> Use $SLUGOWNER/guava in the job downstream

checker/jtreg/stubs/Issue1542Driver.java, framework/src/main/java/org/checkerframework/framework/stub/StubUtil.java
These changes have been move to a pull request against typetools:
https://github.com/typetools/checker-framework/pull/2666
So, revert them here.
=> Revert support .java files as stub files.

build.gradle, checker/bin-devel/build.sh, checker/build.gradle, checker/src/main/java/org/checkerframework/checker/formatter/FormatterAnnotatedTypeFactory.java, checker/src/main/java/org/checkerframework/checker/formatter/FormatterVisitor.java, checker/src/main/java/org/checkerframework/checker/initialization/InitializationVisitor.java, checker/src/main/java/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.java, docs/CHANGELOG.md, framework/build.gradle, framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java, framework/src/main/java/org/checkerframework/framework/flow/CFAbstractTransfer.java, framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java, framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java, settings.gradle
This allows us to remove the annotation-tools dependency.
All changes are marked with "NO-AFU" and a future PR will add support in a separate jar file.
=> Temporarily remove support for "Whole Program Inference"

dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java, framework/tests/value/CompoundAssignment.java
Fixes #121 
javac stores type annotations in TypeMirrors for fields and parameters (and maybe others). #121 uncovered that using that annotated type in a compound assignment cast type leads to incorrect results.
=> Fix compound assignment cast types by removing type annotations

checker/src/test/java/org/checkerframework/checker/test/junit/NullnessJSpecifySamplesTest.java
See
https://github.com/jspecify/jspecify/commit/0d39a0e8bf4ec863a2738835bb2421b25c48f282
and
https://github.com/jspecify/nullness-checker-for-checker-framework/commit/5fe600a48ddd3210cb49794f79bf74a38a94ff45
This change lets `./gradlew :checker:NullnessJSpecifySamples` identify
"real failures" instead of "package org.jspecify.nullness does not
exist."
=> Update to expect version 0.0.0-SNAPSHOT of jspecify.

framework/build.gradle
Builds frequently fail for me with this error:
````
* What went wrong:
Execution failed for task ':framework:jar'.
> Entry org/checkerframework/framework/source/messages.properties is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.3/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.
````
We set duplicate strategies in many other places, but it seems to be missing for framework jars.
=> Set duplicate strategy for framework jars

docs/CHANGELOG.md, framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
The last 2 arguments in `BaseTypeChecker.invokeConstructorFor` have different number of parameters. Checkers using this method will get a `java.lang.IllegalArgumentException` error in runtime.
```
Underlying Exception: java.lang.IllegalArgumentException: wrong number of arguments; java.lang.IllegalArgumentException: wrong number of arguments
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at …
```
=> Fix IllegalArgumentException caused by mismatch of arguments in createFlowAnalysis()

checker/src/main/java/org/checkerframework/checker/nullness/NullnessValue.java
A small refinement to the representation of nullness value in store.
Previously, it looks like this:
where`f` stands for `false` (the key is `isPolyNullNonNull` and `isPolyNullNull`)
Now it looks like this:
where `poly nn` stands for `isPolyNullNonNull`, `poly n` stands for `isPolyNullNull`, `f` stands for `false`.
=> Improve nullness value presentation

build.gradle, checker/bin-devel/build.sh, docs/CHANGELOG.md, docs/manual/troubleshooting.tex
On my computer, `./gradlew assemble` tasks ~4m and `./gradlew fastAssemble` takes ~3m.
I don't think we really need a test for this task since it looks very straightforward.
=> Gradle task `fastAssemble` for executing assemble without Javadoc

checker/jtreg/nullness/stub-typeparams/Box.java, checker/jtreg/nullness/stub-typeparams/NullableBox.java, checker/jtreg/nullness/stub-typeparams/StubTypeParamsClass.java, checker/jtreg/nullness/stub-typeparams/StubTypeParamsClass.out, checker/jtreg/nullness/stub-typeparams/StubTypeParamsClassNbl.java, checker/jtreg/nullness/stub-typeparams/StubTypeParamsClassNbl.out, checker/jtreg/nullness/stub-typeparams/StubTypeParamsMeth.java, checker/jtreg/nullness/stub-typeparams/StubTypeParamsMeth.out, checker/jtreg/nullness/stub-typeparams/StubTypeParamsMethNbl.java, checker/jtreg/nullness/stub-typeparams/StubTypeParamsMethNbl.out, checker/jtreg/nullness/stub-typeparams/box-none.astub, checker/jtreg/nullness/stub-typeparams/box-nonnull.astub, checker/jtreg/nullness/stub-typeparams/box-nullable.astub, checker/jtreg/nullness/stub-typeparams/box-object.astub, checker/jtreg/nullness/stub-typeparams/nullablebox-none.astub, checker/jtreg/nullness/stub-typeparams/nullablebox-nonnull.astub, checker/jtreg/nullness/stub-typeparams/nullablebox-nullable.astub, checker/jtreg/nullness/stub-typeparams/nullablebox-object.astub, docs/CHANGELOG.md, framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileParser.java
This fixes typetools issue 3030.
=> Properly handle explicit "T extends Object" bounds in stub files

checker/jtreg/nullness/stub-typeparams/Box.java, checker/jtreg/nullness/stub-typeparams/NullableBox.java, checker/jtreg/nullness/stub-typeparams/StubWildcards.java, checker/jtreg/nullness/stub-typeparams/StubWildcards.out, checker/jtreg/nullness/stub-typeparams/StubWildcardsNbl.java, checker/jtreg/nullness/stub-typeparams/StubWildcardsNbl.out, checker/jtreg/nullness/stub-typeparams/StubWildcardsNon.java, checker/jtreg/nullness/stub-typeparams/StubWildcardsNon.out, checker/jtreg/nullness/stub-typeparams/box-none.astub, checker/jtreg/nullness/stub-typeparams/box-nonnull.astub, checker/jtreg/nullness/stub-typeparams/box-nullable.astub, checker/jtreg/nullness/stub-typeparams/box-object.astub, checker/jtreg/nullness/stub-typeparams/nullablebox-none.astub, checker/jtreg/nullness/stub-typeparams/nullablebox-nonnull.astub, checker/jtreg/nullness/stub-typeparams/nullablebox-nullable.astub, checker/jtreg/nullness/stub-typeparams/nullablebox-object.astub, docs/CHANGELOG.md, framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileParser.java
This should fix typetools issue 3236.
=> Test wildcards in stub files. Fix unbounded wildcards in stub files.

checker/tests/nullness/ArrayCreationNullable.java, checker/tests/nullness/generics/MixTypeAndDeclAnno.java, framework/src/main/java/org/checkerframework/framework/type/TypeFromMemberVisitor.java
This PR undoes the `addAnnotations` to `replaceAnnotation` changes of https://github.com/eisop/checker-framework/pull/193, to solve the downstream test of https://github.com/opprop/checker-framework-inference/pull/395.
Using `addAnnotations` can add multiple annotations from the same hierarchy, which is required to get the desired error messages about duplicate annotations.
I have tested all the cases and added one new test case.
=> Correctly handle multiple annotations in TypeFromMemberVisitor

framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java, framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
Cherry-pick of https://github.com/opprop/checker-framework/pull/172 to reduce opprop vs eisop differences.
=> Clarify documentation of getTypeDeclarationBounds and use it

framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java, framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeMirror.java
This PR change the method **setEnclosingType** of class **AnnotatedTypeMirror** to public, because in CFI pr: https://github.com/opprop/checker-framework-inference/pull/395, we need to override one method involving this one.
=> Fix enclosing type in deprecated fromNewClass; make AnnotatedTypeMirror.setEnclosingType public

checker/bin-devel/git.pre-commit
To see the effect, should run `./gradlew installGitHooks` locally.
=> Add more files to be ignored by pre-commit hook

checker/tests/regex/Constructors.java, checker/tests/regex/Nested.java
These tests are from
https://github.com/opprop/checker-framework/pull/171 and
https://github.com/opprop/checker-framework/pull/174.
The logic-changes from those PRs were subsumed by later changes, but the tests are good to have.
Co-authored-by: d367wang <d367wang@uwaterloo.ca>
=> Test cases for anonymous and inner class constructors

framework/src/main/java/org/checkerframework/common/basetype/BaseTypeValidator.java
The arguments passed to type.invalid.super.wildcard were not in the right order, so this PR fixes it.
The behavior of this check should be valid as described in: https://github.com/typetools/checker-framework/issues/5006
We encountered a warning in:
```
import java.util.Set;
import org.checkerframework.checker.nullness.qual.*;
public class TestSet {
void foo(Set<Object> s1, Set<? super Object> s2) {
s1.retainAll(s2);
}
}
```
because the capture of `Set<? super Object>` is `Set<Object>` and its implicit upper bound is `@Nullable`.
=> Correct type.invalid.super.wildcard message

checker/src/main/java/org/checkerframework/checker/nullness/NullnessVisitor.java, checker/tests/nullness/InnerCrash.java, docs/CHANGELOG.md
This pr checks the receiver of a new class, including the test case.
Fixes #281.
=> Check the enclosing expression of an object creation for nullness

dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java
Previously, for statement
``` 
d *= i--;
```
The control flow graph is this:
Notice that CFG builder creates one `tempPostfix#num0` variable to represent value `i` before decreasing. However, the ordering is wrong, the assignment of `tempPostfix#num0` is after the decreasing of `i` in the CFG.
After the fix, the CFG is this, which is as expected.
=> Change postfix unary operation ordering in CFG

dataflow/src/main/java/org/checkerframework/dataflow/analysis/AbstractAnalysis.java, dataflow/src/main/java/org/checkerframework/dataflow/analysis/BackwardAnalysisImpl.java, dataflow/src/main/java/org/checkerframework/dataflow/analysis/ForwardAnalysisImpl.java
Field is monotonic-non-null because it is set in subclasses.
In a future cleanup, try making the field final and understand the relation to Analysis better.
=> Only non-null transfer functions should be used

dataflow/src/main/java/org/checkerframework/dataflow/analysis/BackwardTransferFunction.java, framework/src/main/java/org/checkerframework/framework/flow/CFAbstractTransfer.java
For methods in `CFAbstractTransfer.java`, `BackwardTransferFunction.java`, `ForwardTransferFunction.java` with no side effect, add SideEffectFree annotations.
=> Add @SideEffectFree to transfer function files

checker/jtreg/stubs/stub-over-jdk/Issue321.astub, checker/jtreg/stubs/stub-over-jdk/Issue321.java, checker/jtreg/stubs/stub-over-jdk/Issue321.out, framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileElementTypes.java, framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileParser.java
This PR fixes #321 by preventing the parsing of multiple stub files for the same JDK class in the same round.
=> Fix eisop issue #321

framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java, javacutil/src/main/java/org/checkerframework/javacutil/TypeKindUtils.java, javacutil/src/main/java/org/checkerframework/javacutil/TypesUtils.java
- single source of truth for the mapping from a boxed primitive type's fully-qualified name to its type kind.
- removed redundant `toString` call on the result of `TypesUtils.getQualifiedName`
- call `TypesUtils.isImmutableTypeInJdk` in `AnnotatedTypeFactory`
=> Remove duplicate code in AnnotatedTypeFactory and javacutil

checker/tests/nullness-warnredundantannotations/AnnoOnTypeVariableCrashCase.java, framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
Add one null check in the implementation.
If not, the attached testcase will fail.
=> Fix bug in warning about redundant annotations

checker/bin-devel/test-daikon-part1.sh, checker/bin-devel/test-daikon-part2.sh, checker/bin-devel/test-daikon.sh, docs/developer/release/README-release-process.html
This decouples eisop from Daikon changes and allows us to fix type checking problems in Daikon.
=> Use a fork of Daikon and use a fixed commit ID

framework/src/main/java/org/checkerframework/framework/flow/CFAbstractValue.java
#530 causes a failure in Guava tests, surprisingly.
I didn't manage to locally reproduce or minimize the issue.
This size comparison seems like the only difference in behavior to me, so let's see whether this fixes the issue.
File a follow-up issue to make this validation stricter.
=> Temporarily disable stricter size comparison

framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java
This is useful when it's sometimes not clear what checker/visitor is used, e.g. in CI.
Output in a meaningful order, which requires checking the visitor for null twice.
=> Add information about the checker and visitor class to exception reports

javacutil/src/main/java/org/checkerframework/javacutil/ElementUtils.java
Revealed by the improved annotations in https://github.com/eisop/jdk/pull/63
=> Handle possible null return from URI.getPath

checker/tests/nullness/java8/Issue596.java
This should currently pass tests and will pass once https://github.com/eisop/jdk/pull/52 is merged.
=> Use nullable type argument for `AtomicReference`

.gitignore
There is a same entry in line 36.
=> Updates to `.gitignore`

checker/jtreg/nullness/stub-arg/EisopIssue608-bad.astub, checker/jtreg/nullness/stub-arg/EisopIssue608-badstub.out, checker/jtreg/nullness/stub-arg/EisopIssue608-nostub.out, checker/jtreg/nullness/stub-arg/EisopIssue608.java, checker/jtreg/stubs/issue1585/UnknownField.out, checker/jtreg/stubs/issue2059/AnnoNotFound.out, checker/src/main/java/org/checkerframework/checker/nullness/collection-object-parameters-may-be-null.astub, checker/tests/nullness-stubfile/NullnessStubfileMerge.java, framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileElementTypes.java, framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileParser.java
Improve stub file warning messages.
Make stub file work on Java below and above 21, by not including `extends` clauses. Looking through the relevant [JDK commit](https://github.com/openjdk/jdk/commit/17ce0976e442d5fabb14daed40fa9a768989f02e) it looks like `List` is the only class that needs this change in the stub file.
Fixes #608.
=> Improve stub file handling and JDK compatibility

framework/build.gradle
When building the CF from an included build, I'm running into this exception:
````
Exception in thread "main" java.lang.NoClassDefFoundError: org/checkerframework/javacutil/BugInCF
at org.checkerframework.framework.stub.JavaStubifier.process(JavaStubifier.java:73)
at org.checkerframework.framework.stub.JavaStubifier.main(JavaStubifier.java:58)
Caused by: java.lang.ClassNotFoundException: org.checkerframework.javacutil.BugInCF
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
... 2 more
````
When looking at the value of https://github.com/eisop/checker-framework/blob/3764240d1c9fca1ba03c54e74 …
=> Add an extra dependency when building the annotated JDK

checker/jtreg/nullness/Issue6373.java, docs/CHANGELOG.md, framework/build.gradle, framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java, framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java, framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java, framework/src/main/java/org/checkerframework/framework/type/TypeFromMemberVisitor.java
Some timing:
Before this PR:
- using `var`, with init: 165s
- using `var`, assume init: 90s
- using `Object`, with init: 50s
- using `Object`, assume init: 33s
After this PR:
- using `var`, with init: 105s
- using `var`, assume init: 60s
- using `Object`, with init: 45s
- using `Object`, assume init: 30s
There is still a large difference between using `var` and using `Object`, which we should investigate more.
typetools, at https://github.com/typetools/checker-framework/commit/f58c9d93d562c923d2fea17fec978eb2b8040858 (commit before https://github.com/typetools/checker-framework/commit/dc0e62c36818cf76762a4357bbb597d559cbbb28):
- using `var`: 43s
- using `Object`: 42s
typetools, at https://github.com/typetools/checker-framework/commit/dc0e62c36818cf76762a4357bbb597d559cbbb28:
- using …
=> Improve performance of `var` variable declarations

checker/jtreg/nullness/Issue6373.java
Only JDK 11 tests randomly time out in CI.
=> Increase Issue 6373 timeout

checker/jtreg/nullness/Issue1438b.java, checker/jtreg/nullness/Issue1438c.java
For CI stability, mostly on older JDKs.
=> Increase timeouts for `Issue1438b` and `Issue1438c`

framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
This is related to Ontology as it use the value to represent poly type qualifier.
https://github.com/opprop/ontology/pull/130
=> Use `hasAnnotation` for precise check in `PolyTypeScanner`

framework/src/main/java/org/checkerframework/framework/type/TypeVariableSubstitutor.java
It is confusing that the annotations from the copied type are added to the copy again. This just redundantly added the annotations to the set again, being a no-op.
=> Do not add annotations that are already on the copied type

framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java, framework/src/test/java/org/checkerframework/framework/test/junit/ViewpointTestCheckerTest.java, framework/tests/viewpointtest/VarargType.java, framework/tests/viewpointtest/VarargsConstructor.java
=> Set var arg type before calling `viewpointAdaptConstructor`

checker/src/main/java/org/checkerframework/checker/index/lowerbound/LowerBoundAnnotatedTypeFactory.java, checker/src/main/java/org/checkerframework/checker/index/upperbound/UpperBoundAnnotatedTypeFactory.java, checker/src/main/java/org/checkerframework/checker/initialization/InitializationVisitor.java, checker/src/main/java/org/checkerframework/checker/lock/LockAnnotatedTypeFactory.java, checker/src/main/java/org/checkerframework/checker/signedness/SignednessAnnotatedTypeFactory.java, docs/CHANGELOG.md, docs/manual/creating-a-checker.tex, framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java, framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java, framework/src/test/java/org/checkerframework/framework/testchecker/h1h2checker/H1H2AnnotatedTypeFactory.java
Cherry-pick from https://github.com/opprop/checker-framework/pull/215, we can close that PR after merge this one.
=> Deprecate `GenericAnnotatedTypeFactory#addComputedTypeAnnotations(Tree, AnnotatedTypeMirror, boolean)`

docs/CHANGELOG.md, javacutil/src/main/java/org/checkerframework/javacutil/Resolver.java
Fixes typetools 6704.
I tried building with OpenJDK 24-ea+6 locally.
Gradle 8.9 doesn't support Java 24 yet. After first compiling with Java 21 and then with 24-ea+6, I get this error:
````
> Task :javacutil:compileJava FAILED
An exception has occurred in the compiler (24-ea). Please file a bug against the Java compiler via the Java bug reporting page (https://bugreport.java.com) after checking the Bug Database (https://bugs.java.com) for duplicates. Include your program, the following diagnostic, and the parameters passed to the Java compiler in your report. Thank you.
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for org.plumelib.util.WeakIdentityHashMap not found
FAILURE: Build failed with an exception.
````
There is no use of `WeakIdentityHashMap` in `javacutil`, so …
=> Adapt to javac signature change coming in Java 24

docs/CHANGELOG.md, framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java
=> Make `SourceChecker#suppressWarningsString` protected to allow adaptation in subclasses

build.gradle, checker/src/main/java/org/checkerframework/checker/optional/OptionalVisitor.java, dataflow/build.gradle, javacutil/build.gradle
The dependency changes work around the Gradle issue identified in
https://github.com/eisop/checker-framework/pull/806.
The flag changes prepare for new javac warnings.
With this PR, my build with JDK 22 worked. My build with JDK 23
initially got far enough for me to encounter the new warnings but then
started failing with the kind of weirdly nondeterministic Gradle errors
we've seen before:
```
BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 67
```
=> Fix build for JDK 22+

checker/bin-devel/test-jspecify-reference-checker.sh
This will allow us to see that the test actually runs in a PR and, if we merge it, why it fails on `master`.
=> Output JSpecify conformance test details

checker/bin-devel/test-jspecify-reference-checker.sh
By changing into the JSpecify reference checker directory before cloning the JDK. `git-clone-related` now hopefully uses the `jspecify` organization.
Attempt at fixing #860, but will only see whether it worked after merging into `master`.
=> Fix JSpecify reference checker build

.github/workflows/ci.yml, .github/workflows/dependency-generate-and-upload.yml, .github/workflows/dependency-review.yml
I checked the cancelled job, the name of reference for master branch is `CI tests-refs/heads/master' exists`. So instead of using `master/`, we should use `master`
=> Fix CI config for concurrency in master branch

build.gradle, checker/src/test/java/org/checkerframework/checker/testchecker/ainfer/qual/AinferBottom.java, checker/src/test/java/org/checkerframework/checker/testchecker/ainfer/qual/AinferImplicitAnno.java, checker/src/test/java/org/checkerframework/checker/testchecker/ainfer/qual/AinferParent.java, checker/src/test/java/org/checkerframework/checker/testchecker/ainfer/qual/AinferSibling1.java, checker/src/test/java/org/checkerframework/checker/testchecker/ainfer/qual/AinferSibling2.java, checker/src/test/java/org/checkerframework/checker/testchecker/ainfer/qual/AinferSiblingWithFields.java, checker/src/test/java/org/checkerframework/checker/testchecker/ainfer/qual/AinferToIgnore.java, checker/src/test/java/org/checkerframework/checker/testchecker/ainfer/qual/AinferTop.java, framework/src/test/java/org/checkerframework/framework/test/junit/SubtypingEncryptedTest.java, framework/src/test/java/org/checkerframework/framework/testchecker/reflection/qual/PolyTestReflect.java, framework/src/test/java/org/checkerframework/framework/testchecker/reflection/qual/TestReflectBottom.java, framework/src/test/java/org/checkerframework/framework/testchecker/reflection/qual/TestReflectSibling1.java, framework/src/test/java/org/checkerframework/framework/testchecker/reflection/qual/TestReflectSibling2.java, framework/src/test/java/org/checkerframework/framework/testchecker/reflection/qual/TestReflectTop.java, framework/src/test/java/org/checkerframework/framework/testchecker/util/FactoryTestChecker.java
See discussion in https://github.com/eisop/checker-framework/pull/827#discussion_r1722425425
=> Enable Javadoc checks for `src/test` directories

docs/CHANGELOG.md, framework/src/main/java/org/checkerframework/common/initializedfields/InitializedFieldsAnnotatedTypeFactory.java, framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java, framework/src/main/java/org/checkerframework/framework/util/ContractsFromMethod.java, framework/src/main/java/org/checkerframework/framework/util/DefaultContractsFromMethod.java, framework/src/main/java/org/checkerframework/framework/util/NoContractsFromMethod.java
Add `NoContractsFromMethod` implementation and rename previous implementation to `DefaultContractsFromMethod`.
=> Turn `ContractsFromMethod` into an interface

.github/dependabot.yml
https://github.com/eisop/checker-framework/blob/dff6bd53633d8cb00ecb873a2f46de12a1573982/build.gradle#L21 hasn't been updated, even though a new version has been out for over a month.
Let's try whether this change helps.
=> Add root folder to dependabot

.github/workflows/ci.yml
Fail-fast syntax is here https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
=> Stop running new jobs in CI as soon as one of them fails

build.gradle, framework/tests/viewpointtest/PolyConstructor.java, framework/tests/viewpointtest/PolyWithVPA.java, framework/tests/viewpointtest/TestGetAnnotatedLhs.java, framework/tests/viewpointtest/VPAExamples.java, framework/tests/viewpointtest/VarargsConstructor.java
=> Format viewpoint test annotations

checker/build.gradle
This is motivate by failures in https://github.com/eisop/jdk/pull/97
=> Consistently use `doLast`

checker/src/main/java/org/checkerframework/checker/initialization/InitializationFieldAccessSubchecker.java, checker/src/test/java/org/checkerframework/checker/test/junit/AnnotatedForNullnessTest.java, checker/tests/nulless-conservative-defaults/annotatedfornullness/AnnotatedForNullness.java, docs/CHANGELOG.md, framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
To the `InitializationFieldAccessSubchecker`.
Fixes #982.
=> Also handle the `InitializationChecker` as upstream checker

checker/src/main/java/org/checkerframework/checker/initialization/InitializationChecker.java, checker/src/main/java/org/checkerframework/checker/initialization/InitializationFieldAccessSubchecker.java, checker/tests/nulless-conservative-defaults/annotatedfornullness/AnnotatedForNullness.java
Also handles `InitializationChecker` in abstract `InitializationChecker` class.
If don't handle it here, I found the following case will issue error.
How to reproduce:
1. remove annotatedFor("nullness") and use AnnotatedFor("intialization") in the following two places. This should make sure the initialization don't use conservative defaults. https://github.com/eisop/jdk/blob/b073fe213273118a9997ce3fccd1f36e103f5b04/src/java.base/share/classes/java/lang/package-info.java#L71 
https://github.com/eisop/jdk/blob/b073fe213273118a9997ce3fccd1f36e103f5b04/src/java.base/share/classes/java/lang/Character.java#L194
2. test case
Command: `./checker/bin/javac -processor nullness -AuseConservativeDefaultsForUncheckedCode=bytecode,-source Test.java`
```
import …
```
=> Handle the `InitializationChecker` as upstream checker

docs/manual/map-key-checker.tex
Using `v` as the argument for `containsKey` seems odd. 
Brought up by Sam Huang when he tried to look at the manual for KeyFor checker.
=> Rename variable in Map Key Checker manual section

checker/bin-devel/test-misc.sh, checker/build.gradle
Merge with https://github.com/eisop/templatefora-checker/pull/1
=> Add CI test for the `templatefora-checker`

framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
The method parameters are adapted at https://github.com/eisop/checker-framework/blob/e5589987c57f0d6a60f97bcfd520bdad182a8bb4/framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java#L2540.
Adapt it again will cause error and we directly get the parameter type after adaptation in this change.
=> Directly get adapted parameter type

framework/src/main/java/org/checkerframework/framework/util/typeinference8/util/CheckedExceptionsUtil.java, framework/tests/all-systems/java8inference/ExceptionInLambdaTest.java
Fixes #1174 , which was caused by a few typos in type inference of generic exception types.
Specifically, the framework, upon encountering a statement `throw e;` attempted to get the type of the entire statement instead of the type of `e`, causing an NPE. Also, run-time exceptions were inferred as non-run-time exceptions and vice versa.
=> Fix inference of generic exception types

framework/src/main/java/org/checkerframework/framework/type/SubtypeIsSubsetQualifierHierarchy.java
I tried suppressing "argument.type.incompatible", "all:argument.type.incompatible", and "nullness:argument.type.incompatible", none of which suppressed all three warnings.
This is odd behavior, not how suppression should work.
When I try locally, I get:
````
./gradlew :framework:checkNullness
> Task :framework:checkNullness
checker-framework/framework/src/main/java/org/checkerframework/framework/type/SubtypeIsSubsetQualifierHierarchy.java:39: warning: [nullness:unneeded.suppression] warning suppression "nullness:argument.type.incompatible" is not used by NullnessChecker
@SuppressWarnings("nullness:argument.type.incompatible") // TODO: EISOP Issue #1193
^
error: warnings found and -Werror specified
1 error
1 warning
````
=> Work around EISOP Issue #1193

checker/bin-devel/git.pre-commit, checker/bin-devel/test-misc.sh, checker/jtreg/nullness/defaultsPersist/Classes.java, checker/jtreg/nullness/defaultsPersist/Constructors.java, checker/jtreg/nullness/defaultsPersist/Fields.java, checker/jtreg/nullness/defaultsPersist/Methods.java, checker/jtreg/nullness/inheritDeclAnnoPersist/Extends.java, checker/jtreg/nullness/inheritDeclAnnoPersist/Implements.java, docs/examples/BazelExample/Makefile, docs/examples/MavenExample/Makefile, docs/examples/errorprone/Makefile, docs/examples/lombok/Makefile
Related to #1198. This just stops running the broken tests.
@thisisalexandercook The tests will need some restructuring to nicely separate the two versions of the tests while sharing as much common code as possible.
=> Skip jtreg tests that require old Class-File API on JDK >= 25
