framework/src/main/java/org/checkerframework/framework/type/poly/AbstractQualifierPolymorphism.java
The test case which is failing is PolyReturn.java, which is related to framework/src/main/java/org/checkerframework/framework/type/poly/AbstractQualifierPolymorphism.java.
This PR just reverts the commit 8f373dae47b8ef128e8d3dd76428531562c923e4. I'm not 100% sure but it looks like that that commit was resolving the same issue as https://github.com/typetools/checker-framework/pull/2504.
=> Fix taintingtest

docs/examples/MavenExample-framework-all/pom.xml, docs/examples/MavenExample/pom.xml
Signed-off-by: Shubham Raj <shubhamraj1in@gmail.com>
=> Modify MavenExample-framework-all POM to compile on Java9+

docs/examples/MavenExample-framework-all/pom.xml, docs/examples/MavenExample/pom.xml
@wmdietl 
On further investigation, I found that we don't even need the error_prone_core.jar
Thanks.
=> error_prone_core not needed

azure-pipelines.yml, build.gradle, checker/bin-devel/wpi-plumelib/test-wpi-plumelib.sh, checker/build.gradle, checker/tests/command-line/issue618/Makefile, checker/tests/mustcall/OwningParams.java, checker/tests/nullness-extra/compat/Makefile, checker/tests/nullness-extra/issue594/Makefile, checker/tests/nullness-extra/multiple-errors/Makefile, checker/tests/nullness-extra/package-anno/Makefile, checker/tests/nullness-extra/shorthand/Makefile, checker/tests/regex/RawTypeTest.java, docs/examples/MavenExample/Makefile, docs/examples/fenum-extension/Makefile, docs/examples/subtyping-extension/Makefile, docs/examples/units-extension/Makefile, docs/tutorial/tests/ant.xml, framework/src/main/java/org/checkerframework/framework/util/CheckerMain.java, framework/tests/annotationclassloader/Makefile, javacutil/src/main/java/org/checkerframework/javacutil/Resolver.java, javacutil/src/main/java/org/checkerframework/javacutil/TreeUtils.java
Cleanups to Java 16 support. Make Java 17 work cleanly.
=> Support Java 17

framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
Split off from #146 / #148 to support NullMarked.
=> Support adding declaration annotation aliases using annotation names

checker-qual/src/main/java/org/checkerframework/framework/qual/DefaultQualifier.java, docs/CHANGELOG.md, framework/src/main/java/org/checkerframework/framework/util/defaults/Default.java, framework/src/main/java/org/checkerframework/framework/util/defaults/QualifierDefaults.java, framework/tests/h1h2checker/pkg1/PackageDefaulting.java, framework/tests/h1h2checker/pkg1/package-info.java, framework/tests/h1h2checker/pkg1/pkg2/PackageDefaulting.java
Split off from #146 / #148 to support NullMarked.
=> Support DefaultQualifiers that do not apply to subpackages

checker/src/main/java/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.java, docs/manual/nullness-checker.tex
I need to actually test this on our depot, not to mention get permission to add the experimental annotation in the first place :) But given that there are a few moving pieces, I'm trying to reach out to the various people involved to see if the overall idea seems sound.
=> Recognize an experimental protobuf @PolyNull annotation.

checker/tests/regex/Issue3281.java, dataflow/manual/content.tex, dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java, dataflow/src/main/java/org/checkerframework/dataflow/cfg/node/AbstractNodeVisitor.java, dataflow/src/main/java/org/checkerframework/dataflow/cfg/node/ExpressionStatementNode.java, dataflow/src/main/java/org/checkerframework/dataflow/cfg/node/NodeVisitor.java, dataflow/tests/live-variable/Expected.txt, docs/CHANGELOG.md, framework/src/main/java/org/checkerframework/framework/flow/CFAbstractTransfer.java
Moved from https://github.com/opprop/checker-framework/pull/161
=> Add ExpressionStatementNode

framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
Applying the same change in opprop: https://github.com/opprop/checker-framework/pull/204
=> Fix visitor rule for invalid polymorphic qualifier use

checker/tests/tainting/NestedAnonymous.java, docs/CHANGELOG.md, framework/src/main/java/org/checkerframework/framework/util/element/VariableApplier.java
=> Handle nested anonymous classes in field initializers

dataflow/src/main/java/org/checkerframework/dataflow/analysis/AbstractAnalysis.java, framework/src/main/java/org/checkerframework/framework/util/defaults/Default.java
Small fix towards the documentation as discussed in today's meeting.
=> Fix documentation and message text

checker/src/main/java/org/checkerframework/checker/fenum/FenumAnnotatedTypeFactory.java, checker/src/main/java/org/checkerframework/checker/formatter/FormatterAnnotatedTypeFactory.java, checker/src/main/java/org/checkerframework/checker/mustcall/MustCallAnnotatedTypeFactory.java, checker/src/main/java/org/checkerframework/checker/nullness/KeyForAnnotatedTypeFactory.java, checker/src/main/java/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.java, checker/src/main/java/org/checkerframework/checker/units/UnitsAnnotatedTypeFactory.java, framework/src/test/java/org/checkerframework/framework/testchecker/util/EvenOddChecker.java
I tested all test cases and all of them passed.
=> Change some methods from public to protected

dataflow/tests/busyexpr/Expected.txt, dataflow/tests/busyexpr/Test.java
`new Integer(xx)` is deprecated, use another way to test object creation
=> Fix deprecation warning in busy expression analysis test

checker/tests/nullness/Issue5189a.java, checker/tests/nullness/Issue5189b.java, docs/CHANGELOG.md, framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java
This fixes typetools issue 5189.
=> Fix how vararg, anonymous class constructor parameters are handled

docs/CHANGELOG.md, framework/src/main/java/org/checkerframework/framework/type/AbstractViewpointAdapter.java, framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java, framework/src/main/java/org/checkerframework/framework/type/ViewpointAdapter.java, framework/src/test/java/org/checkerframework/framework/test/junit/ViewpointTestCheckerTest.java, framework/src/test/java/viewpointtest/ViewpointTestAnnotatedTypeFactory.java, framework/src/test/java/viewpointtest/ViewpointTestChecker.java, framework/src/test/java/viewpointtest/ViewpointTestViewpointAdapter.java, framework/src/test/java/viewpointtest/quals/A.java, framework/src/test/java/viewpointtest/quals/B.java, framework/src/test/java/viewpointtest/quals/Bottom.java, framework/src/test/java/viewpointtest/quals/PolyVP.java, framework/src/test/java/viewpointtest/quals/ReceiverDependentQual.java, framework/src/test/java/viewpointtest/quals/Top.java, framework/tests/viewpointtest/PolyConstructor.java, framework/tests/viewpointtest/PolyWithVPA.java, framework/tests/viewpointtest/VPAExamples.java
Cherry-pick of https://github.com/opprop/checker-framework/pull/69 and https://github.com/opprop/checker-framework/pull/140 plus misc clean-ups to get viewpoint adaptation into eisop.
=> Add ViewpointAdapter

checker/tests/nullness/EisopIssue308.java, docs/CHANGELOG.md, framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java
=> Improve handling of nested, anonymous constructors

dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java
1. add missing `handleArtificialTree()` calls
2. remove redundant object creation
=> CFG Translation Phase 1 minor improvements

checker/src/main/java/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.java, checker/tests/nullness-nullmarked/parentandchildpackage/NotNullMarkedBecauseChildPackage.java, checker/tests/nullness-nullmarked/parentandchildpackage/package-info.java, checker/tests/nullness-nullmarked/singlepackage/NullMarkedBecausePackageIs.java, checker/tests/nullness-nullmarked/singlepackage/package-info.java, docs/manual/nullness-checker.tex
See https://github.com/jspecify/jspecify/issues/260 and related PR.
=> Add aliases for new JSpecify package

azure-pipelines.yml, checker/bin-devel/build.sh, checker/bin-devel/test-jspecify.sh
Also, remove currently redundant `_next` CI targets.
=> Move JSpecify build to separate tests

framework/src/main/java/org/checkerframework/framework/util/defaults/QualifierDefaults.java
Manually ensure auto-merge requires the correct jobs.
=> Fix formatting

framework/src/main/java/org/checkerframework/framework/util/defaults/QualifierDefaults.java
Extract `DefaultApplierElementImpl` from one level of nesting.
=> Refactor `QualifierDefaults`

build.gradle, checker/build.gradle, dataflow/build.gradle
Fix The org.gradle.api.plugins.BasePluginConvention type has been deprecated warning.
=> Replace deprecated Gradle APIs

build.gradle, framework/src/main/java/org/checkerframework/common/reflection/DefaultReflectionResolver.java
Use local `Symbol.getEnclosedElements` helper.
=> Update to errorprone 2.21.1

build.gradle
Add cloneAndBuildJspecify task and make test depends on it.
This make ./gradlew test will success.
=> Clone JSpecify when needed and add test dependency

javacutil/src/main/java/org/checkerframework/javacutil/TreeUtils.java
I built 3.40.0-eisop1 with Java 21.
Using that artifact in #630 leads to a failure:
````
error: SourceChecker.typeProcess: unexpected Throwable (NoSuchMethodError) while processing /home/wdietl/workspaces-local/checker-framework/docs/examples/errorprone/src/main/java/com/example/Demo.java; message: 'com.sun.tools.javac.tree.JCTree$JCFieldAccess com.sun.tools.javac.tree.TreeMaker.Select(com.sun.tools.javac.tree.JCTree$JCExpression, com.sun.tools.javac.code.Symbol)'
; The Checker Framework crashed.  Please report the crash.  Version: Checker Framework 3.40.0-eisop1. 
Checker: class org.checkerframework.checker.nullness.KeyForSubchecker
Visitor: class org.checkerframework.common.basetype.BaseTypeVisitor
Compilation unit: /home/wdietl/workspaces-local/checker-framework/docs/examples/errorprone …
```
=> Always access `TreeMaker#Select` reflectively

checker/src/main/java/org/checkerframework/checker/initialization/InitializationStore.java, checker/tests/nullness-initialization/EisopIssue635.java, docs/CHANGELOG.md
Fixes #635.
Follow-up work in #637.
=> Do not use `thisValue` when it is the NullType

framework/src/main/java/org/checkerframework/framework/type/ElementAnnotationApplier.java, framework/src/main/java/org/checkerframework/framework/util/element/ClassTypeParamApplier.java, framework/src/main/java/org/checkerframework/framework/util/element/ElementAnnotationUtil.java, framework/src/main/java/org/checkerframework/framework/util/element/MethodApplier.java, framework/src/main/java/org/checkerframework/framework/util/element/MethodTypeParamApplier.java, framework/src/main/java/org/checkerframework/framework/util/element/ParamApplier.java, framework/src/main/java/org/checkerframework/framework/util/element/SuperTypeApplier.java, framework/src/main/java/org/checkerframework/framework/util/element/TargetedElementAnnotationApplier.java, framework/src/main/java/org/checkerframework/framework/util/element/TypeDeclarationApplier.java, framework/src/main/java/org/checkerframework/framework/util/element/TypeParamElementAnnotationApplier.java, framework/src/main/java/org/checkerframework/framework/util/element/TypeVarUseApplier.java, framework/src/main/java/org/checkerframework/framework/util/element/VariableApplier.java
=> Cleanups in framework/util/element

build.gradle, docs/CHANGELOG.md, framework/build.gradle, framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java, framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileElementTypes.java
It added over 500kB to `checker.jar`.
=> Remove the dependency on the classgraph library

docs/CHANGELOG.md, framework/src/main/java/org/checkerframework/framework/util/AtmLubVisitor.java, framework/tests/all-systems/Issue6438.java
This might be unsound and should be investigated further.
=> Work around `IndexOutOfBoundsException` in `AtmLubVisitor`

checker-qual/build.gradle, gradle/wrapper/gradle-wrapper.properties, gradlew.bat
Note that #699 did not update `gradlew.bat`.
=> Update gradle to 8.6

framework/src/main/java/org/checkerframework/framework/util/AtmLubVisitor.java, framework/tests/all-systems/Issue703.java
=> Propagate if a type argument is un-inferred through LUB computations

dataflow/build.gradle
=> Fix gradle warnings in Dataflow test

checker/src/main/java/org/checkerframework/checker/initialization/InitializationVisitor.java, javacutil/src/main/java/org/checkerframework/javacutil/ElementUtils.java, javacutil/src/main/java/org/checkerframework/javacutil/TreeUtils.java
Remove local variable as mentioned #763
=> Rename local variables and clean up some code

docs/manual/nullness-checker.tex
=> [nullness] Forward references and typo fixes

javacutil/src/main/java/org/checkerframework/javacutil/Resolver.java
Follow-up to https://github.com/eisop/checker-framework/commit/56e839d8b349308c14938e6886e494be79c57fdd
https://github.com/eisop/checker-framework/pull/806
=> Update call site for javac signature change

javacutil/src/main/java/org/checkerframework/javacutil/Resolver.java
The change was backported to JDK 23: https://bugs.openjdk.org/browse/JDK-8334258
=> Adapt to javac signature change coming in JDK 23

docs/manual/introduction.tex
=> Manual entry for `-AignoreTargetLocations`

docs/CHANGELOG.md, docs/developer/release/README-release-process.html, docs/examples/errorprone/build.gradle, docs/manual/external-tools.tex
=> Also add `checker-qual` to the Checker Framework gradle plugin call

checker/src/main/java/org/checkerframework/checker/nullness/NullnessNoInitVisitor.java, checker/tests/nullness/java17/NullnessInstanceOf.java, docs/CHANGELOG.md
fixes #1058 by adding support for instanceof pattern variables to the nullness visitor.
=> Instanceof pattern variable nullness annotation checks

framework/src/main/java/org/checkerframework/common/initializedfields/InitializedFieldsAnnotatedTypeFactory.java, framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java
Draft PR ot see if fixes plume lib problem.
=> Fix and optimize `InitializedFieldsAnnotatedTypeFactory#defaultValueIsOK`

checker-qual/src/main/java/org/checkerframework/checker/formatter/qual/ConversionCategory.java, checker-qual/src/main/java/org/checkerframework/checker/i18nformatter/qual/I18nConversionCategory.java, checker-qual/src/main/java/org/checkerframework/framework/qual/ParametricTypeVariableUseQualifier.java, checker-qual/src/main/java/org/checkerframework/framework/qual/PolymorphicQualifier.java, checker-qual/src/main/java/org/checkerframework/framework/qual/SubtypeOf.java
Merge with https://github.com/eisop/jdk/pull/115
=> Remove `AnnotatedFor` on annotations in `checker-qual`

build.gradle, checker/bin-devel/test-misc.sh, checker/build.gradle, docs/CHANGELOG.md
=> Use `CloneTask` for cloning `templateforaChecker` and `demos`

docs/CHANGELOG.md, javacutil/src/main/java/org/checkerframework/javacutil/Resolver.java
Fixes #1180.
Tests on JDK 25 will be performed in #1190.
=> Work on Java 25: reflectively create a `DiscardDiagnosticHandler`

.github/workflows/ci.yml
=> Run CI daily

.github/dependabot.yml, .gitignore, docs/examples/Makefile, docs/examples/nullaway/Makefile, docs/examples/nullaway/build.gradle, docs/examples/nullaway/src/main/java/com/example/Demo.java, docs/manual/contributors.tex
This PR fixes authorship issues found in PR #1149.
Fixes #1242.
=> Add a NullAway example

checker/tests/lock/ChapterExamples.java, checker/tests/nullness/java-unsound/Figure3.java, framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java, framework/tests/all-systems/InferTypeArgs.java, framework/tests/all-systems/WildcardInReturn.java
Follow-up work to #1227 and #1275.
=> Change `Void` to `NullType` in comments and Javadoc
